s1 = "   wE are  Learning   Python "
print("Lowercase:",s1.lower())
print("Uppercase:",s1.upper())
print("check string is lower",s1.islower())
print("check string is upper",s1.isupper())
print("swapcase:",s1.swapcase())
print("titleoutput:",s1.title())
print("capitalize:",s1.capitalize())
print("count of n",s1.count("n"))
print("count of ""java",s1.count("java"))
print("index of E",s1.index("E"))
print("index of e",s1.index("e"))
print("index of n",s1.index("n"))
print("find of n",s1.find("F"))
print("replace words:",s1.replace("python ","Java").replace('n','m').lower())
print("split", s1.split("#"))
print("split", s1.split("e"))
print("join method"," ".join(s1))
#print("join method",join(s1)."#")- invalid format
print("strip method",s1.strip())
print("strip method",s1.lstrip())
print("strip method",s1.rstrip())