a= "Hello, Work hard, work smart"
b= "THEY ARE GOOD"
c=  "Hello, Work hard, Work smart"
print("1.", a.upper())
print("2.", a.lower())
print("3.",a. isupper())
print("4.",b.isupper())
print ("5.", a. islower())
print("6.", a.title())
print("7.", a.count("work"))
print("8.", a.count("work" or "Work"))
print("9.", a.count("work" and "Work"))
print("10", c.count("work" or "Work"))
print("11", b.swapcase())
print("12.", a.swapcase())
print("13.",b.capitalize())
print("14.","Count of work:",a.count("work"),"Count of o:",a.count("o"))
print("15.", a.index('o'),a.index('work') )
print("16.", a.index('ork'))
print("17.", a.replace('work','Brain'))
print("18.", a.split())
print("19.", a.split('o'))
d= "friends".join(b)
print("20.",d )